[package]
name = "fetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
reqwest = "0.11"
select = "0.5"
tokio = { version = "1", features = ["full"] }
scraper = "0.19.0"